### ISSUE TITLE
`Nette\Forms\Form` is not `Nette\Application\UI\Form` but fails silently

### ISSUE THREAD

**Issue by MaPePeR** [nette/forms#147] opened 2017-03-16 15:42 UTC
- bug report? no
- feature request? yes
- version: 2.4

### Description
I'm just starting to learn Nette and after looking through documentation and example code i tried to setup a very simple Form. The Form rendered fine, but the `onSuccess` handler was never executed and it took me a very long time to figure out the problem:
I created a `Nette\Forms\Form`-Object instead of the `Nette\Application\UI\Form`-Object that i was supposed to use.
It would be great if there would be an Exception if one tries to use the `Nette\Forms\Form` like a `Nette\Application\UI\Form`. Or at least mention this pitfall in the documentation somewhere.

Thanks.

### Steps To Reproduce
1. Be very inexperienced with the Nette Framework
2. Write code like this in your Presenter:
```php
	public function createComponentMyForm() {
		$form = new Nette\Forms\Form;//<- This is the Problem. 
		$form->addSubmit('submit_it', "Submit!");
		$form->onSuccess[] = [$this, 'formSucceeded'];
		return $form;
	}
	
	public function formSucceeded($form, $values) {
		//This will never be called
	}
```
3. Get frustated

**Comment by lucien144** [comment] 2017-05-10 07:42
Well, I reckon it's documented pretty well... https://doc.nette.org/en/2.4/forms#toc-forms-in-presenters. But in general I have to agree with you, this is one of the most common blockers for beginners...

**Comment by Majkl578** [comment] 2017-05-10 13:10
This is by design unfortunately, nothing to fix here...

**Comment by f3l1x** [comment] 2017-06-18 12:35
What about rename it to `AppForm`, do you think it's better?

**Comment by Majkl578** [comment] 2017-06-18 17:59
That would be a massive BC break with almost no added value (as this behavior is well documented). (Btw "App" in "AppForm" would duplicate the namespace it lives in and thus the class name as well - Nette\Application\UI\Form.)

**Comment by f3l1x** [comment] 2017-06-18 18:38
@Majk578 I agree. I think we can close it.

**Comment by MaPePeR** [comment] 2017-06-18 20:32
Maybe you could add the hint about the two different kind of `Form` to the [First Form](https://doc.nette.org/en/2.4/forms#toc-first-form)-Section of the documentation as well, because that is where i started?

**Closed** 2021-01-19 00:22 UTC
